// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protocol.proto

#include "protocol.pb.h"
#include "protocol.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace protocol {

static const char* DatabaseService_method_names[] = {
  "/protocol.DatabaseService/sendRequest",
};

std::unique_ptr< DatabaseService::Stub> DatabaseService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DatabaseService::Stub> stub(new DatabaseService::Stub(channel));
  return stub;
}

DatabaseService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_sendRequest_(DatabaseService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DatabaseService::Stub::sendRequest(::grpc::ClientContext* context, const ::protocol::Request& request, ::protocol::Responce* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_sendRequest_, context, request, response);
}

void DatabaseService::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::protocol::Request* request, ::protocol::Responce* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, std::move(f));
}

void DatabaseService::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::Responce* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, std::move(f));
}

void DatabaseService::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::protocol::Request* request, ::protocol::Responce* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, reactor);
}

void DatabaseService::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::Responce* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::Responce>* DatabaseService::Stub::AsyncsendRequestRaw(::grpc::ClientContext* context, const ::protocol::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::Responce>::Create(channel_.get(), cq, rpcmethod_sendRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::protocol::Responce>* DatabaseService::Stub::PrepareAsyncsendRequestRaw(::grpc::ClientContext* context, const ::protocol::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::Responce>::Create(channel_.get(), cq, rpcmethod_sendRequest_, context, request, false);
}

DatabaseService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DatabaseService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DatabaseService::Service, ::protocol::Request, ::protocol::Responce>(
          [](DatabaseService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::protocol::Request* req,
             ::protocol::Responce* resp) {
               return service->sendRequest(ctx, req, resp);
             }, this)));
}

DatabaseService::Service::~Service() {
}

::grpc::Status DatabaseService::Service::sendRequest(::grpc::ServerContext* context, const ::protocol::Request* request, ::protocol::Responce* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace protocol

